# documentation: https://github.com/dgtlmoon/changedetection.io/
# slogan: Website change detection monitor and notifications.
# tags: web, alert, monitor
# logo: svgs/changedetection.png
# port: 5000

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    environment:
      - SERVICE_FQDN_CHANGEDETECTION_5000
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - BASE_URL=${BASE_URL:-$SERVICE_FQDN_CHANGEDETECTION}
      - PLAYWRIGHT_DRIVER_URL=${PLAYWRIGHT_DRIVER_URL:-ws://browser-sockpuppet-chrome:3000}
      # Hides the `Referer` header so that monitored websites can't see the changedetection.io hostname.
      - HIDE_REFERER=${HIDE_REFERER:-true}
      # Default number of parallel/concurrent fetchers
      - FETCH_WORKERS=${FETCH_WORKERS:-10}
      # Absolute minimum seconds to recheck
      - MINIMUM_SECONDS_RECHECK_TIME=${MINIMUM_SECONDS_RECHECK_TIME:-3}
      # For complete privacy if you don't want to use the 'check version' / telemetry service
      - DISABLE_VERSION_CHECK=${DISABLE_VERSION_CHECK:-true}
      # Maximum height of screenshots
      - SCREENSHOT_MAX_HEIGHT=${SCREENSHOT_MAX_HEIGHT:-16000}
      # Timezone
      - TZ=${TZ:-UTC}
      # Log level
      - LOGGER_LEVEL=${LOGGER_LEVEL:-DEBUG}
    depends_on:
      browser-sockpuppet-chrome:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 5s
      timeout: 20s
      retries: 10

  browser-sockpuppet-chrome:
    hostname: browser-sockpuppet-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    # SYS_ADMIN might be too much, but it can be needed on your platform
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=${SCREEN_WIDTH:-1920}
      - SCREEN_HEIGHT=${SCREEN_HEIGHT:-1024}
      - SCREEN_DEPTH=${SCREEN_DEPTH:-16}
      - MAX_CONCURRENT_CHROME_PROCESSES=${MAX_CONCURRENT_CHROME_PROCESSES:-10}
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  changedetection-data: